#!/usr/bin/env node
// Generates docs/SOURCES.md (human-readable source log) from content/sources.json.
//   node tools/audit/sources_md.mjs        (npm run sources)
// content/sources.json itself is built by tools/audit/build_sources.mjs from the rulings + verify results.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const sources = JSON.parse(fs.readFileSync(path.join(ROOT, 'content/sources.json'), 'utf8'));
const TYPES = [
  ['quran', 'Quran — القرآن الكريم'],
  ['hadith', 'Hadith — الحديث النبوي'],
  ['madhhab', 'Madhhab references — مراجع المذاهب الأربعة'],
  ['contemporary', 'Contemporary fiqh bodies & fatwas — المجامع والهيئات المعاصرة'],
  ['other', 'Bible (KJV + Van Dyck) & Christian-practice sources — الكتاب المقدس ومصادر الممارسة المسيحية']
];
const esc = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
const out = [];
out.push('# Source log — سجل المصادر', '');
out.push('> Generated by `node tools/audit/sources_md.mjs` from [`content/sources.json`](../content/sources.json). Do not edit by hand.');
out.push('> يُولَّد آلياً من `content/sources.json`؛ لا تعدّله يدوياً.', '');
out.push('**Verified** means a machine check (`tools/audit/verify.mjs`) matched the text letter-by-letter (with harakat) against the source, or the auditor matched it by hand (`tools/audit/manual_verifications.json`). It does **not** mean a scholar reviewed the ruling: none of the 18 rulings has been reviewed by a human scholar yet.', '');
out.push('«موثّق» يعني أن النص طوبق آلياً (أو يدوياً) مع مصدره حرفاً بحرف، ولا يعني أن عالماً راجع الحكم؛ لم تُراجَع الأحكام بعدُ من عالم بشري.', '');
out.push('| Type | Entries | Verified | Not verified (needs a human) |', '|---|---|---|---|');
for (const [type, title] of TYPES) {
  const list = sources.filter((s) => s.type === type);
  out.push(`| ${title} | ${list.length} | ${list.filter((s) => s.verified).length} | ${list.filter((s) => !s.verified).length} |`);
}
out.push(`| **Total** | **${sources.length}** | **${sources.filter((s) => s.verified).length}** | **${sources.filter((s) => !s.verified).length}** |`, '');
for (const [type, title] of TYPES) {
  const list = sources.filter((s) => s.type === type);
  if (!list.length) continue;
  out.push(`## ${title}`, '');
  out.push('| # | Citation | Link | Verified | Used in | How it was checked |', '|---|---|---|---|---|---|');
  list.forEach((s, i) => {
    const link = s.url ? `[link](${s.url})` : '—';
    out.push(`| ${i + 1} | ${esc(s.citation)} | ${link} | ${s.verified ? '✅' : '⏳'} | ${esc((s.used_in || []).join(', '))} | ${esc(s.verified_how)} |`);
  });
  out.push('');
}
fs.writeFileSync(path.join(ROOT, 'docs/SOURCES.md'), out.join('\n'));
console.log(`docs/SOURCES.md written (${sources.length} entries)`);
